networks:
  network:
    name: ${PROJECT_NAME}_network

services:
  redis:
    container_name: ${PROJECT_NAME}-redis
    image: redis:7.4-alpine
    networks:
      - network
    expose:
      - ${REDIS_PORT}
    volumes:
      - redis_data:/var/lib/redis/data/
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    restart: always

  asgi:
    container_name: ${PROJECT_NAME}-asgi
    build:
      context: ./src/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ${STATIC_PATH}:/static
      - ${MEDIA_PATH}:/media
      - ${LOG_PATH}:/logs
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "${ASGI_PORT}:${ASGI_PORT}"
    networks:
      - network
    restart: always

volumes:
  redis_data:
    name: ${PROJECT_NAME}_redis_data
